---
language: c
services:
  - docker

# Run everything in a Fedora container (created in before_install) so
# that we're not fighting with deps on two distros
env:
  DOCKER_RUN="docker run -v $PWD:/rpminspect --workdir /rpminspect rpminspect/test-env"

before_install:
  - docker build -t rpminspect/test-env -f Dockerfile.test .

script:
  - $DOCKER_RUN ./autogen.sh
  - $DOCKER_RUN ./configure --enable-code-coverage
  - $DOCKER_RUN make check-code-coverage
  - $DOCKER_RUN make distcheck

after_success:
  # This also needs to run from inside the container, so that gcov and gcc match
  # The container needs some environment variables from the host, see https://docs.travis-ci.com/user/coveralls/
  - docker run -v $PWD:/rpminspect --workdir /rpminspect -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH" rpminspect/test-env coveralls --exclude tests --gcov-options '\-lp'
