# Set up an environment for running the tests.
FROM fedora:rawhide
RUN dnf -y install 'dnf-command(builddep)'
RUN dnf -y install ksh rc tcsh zsh

# Start with the buildreqs from the spec file
# Fake enough of the template processing to get dnf to read rpminspect.spec.in as a spec file
COPY rpminspect.spec.in /rpminspect.spec
COPY changelog /root/rpmbuild/SOURCES/changelog
RUN sed -i -e 's|%%VERSION%%|1.0|g' -e 's|%%RPMDATE%%|$(date +"%a %b %d %Y")|g' /rpminspect.spec
RUN dnf -y builddep --spec rpminspect.spec

# Add additional test dependencies
RUN dnf -y install CUnit CUnit-devel valgrind gcovr python3-pyyaml python3-pip rpm-build desktop-file-utils glibc.i686 glibc-devel.i686 kernel-core kernel-devel
RUN pip-3 install cpp-coveralls rpmfluff
