# Set up an environment for running the tests.
FROM fedora:31
RUN dnf -y install 'dnf-command(builddep)'

# Start with the buildreqs from the spec file
# Fake enough of the template processing to get dnf to read rpminspect.spec.in as a spec file
COPY rpminspect.spec.in /rpminspect.spec
COPY changelog /root/rpmbuild/SOURCES/changelog
RUN sed -i -e 's|%%VERSION%%|1.0|g' -e 's|%%RPMDATE%%|$(date +"%a %b %d %Y")|g' /rpminspect.spec
RUN dnf -y builddep --spec rpminspect.spec

# Add additional test dependencies
RUN dnf -y install CUnit-devel valgrind gcovr python3-pip rpm-build desktop-file-utils
RUN pip-3 install cpp-coveralls rpmfluff
