name: Alt Linux

on:
    push:
        branches: [ main ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'

jobs:
    linux:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["alt:latest"]

        container:
            image: ${{ matrix.container }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Requirements before the git clone can happen
            - name: git clone requirements
              run: |
                  apt-get update
                  apt-get install -y git
                  git config --global --add safe.directory /__w/rpminspect/rpminspect

            # This means clone the git repo
            - uses: actions/checkout@v3

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  # Install make(1) so we can use the instreqs target
                  apt-get install -y make

                  # Install build dependencies and set up the target
                  make instreqs

                  # Build the software and run the test suite
                  # Strike default ALT Linux macros in rpmbuild
                  find /usr/lib/rpm -type f | xargs sed -i -e '/^%vendor/d'

                  # Set the build up to run as a non-root user for Alt Linux
                  SRC="$(pwd)"
                  HME="/home/tester"
                  DST="${HME}/$(basename "${SRC}")"
                  cp -pr "${SRC}" "${HME}"
                  chown -R tester:tester "${DST}"

                  # Run the build and test suite as non-root
                  cd "${DST}"
                  sudo -u tester meson setup build --werror -D b_buildtype=debug -D b_coverage=true
                  sudo -u tester ninja -C build -v
                  sudo -u tester meson test -C build -v
                  sudo -u tester ninja -C build coverage && ( curl -s https://codecov.io/bash | bash ) || :
