name: CentOS 7

on:
    push:
        branches: [ main ]
        paths-ignore:
            - AUTHORS.md
            - CC-BY-4.0.txt
            - CHANGES.md
            - CODE_OF_CONDUCT.md
            - CONTRIBUTING.md
            - COPYING
            - COPYING.LIB
            - HISTORY
            - LICENSE-2.0.txt
            - MISSING
            - MIT.txt
            - README.md
            - RELEASE
            - TODO
            - 'contrib/**'
            - 'data/**'
            - 'doc/**'
            - 'po/**'
            - 'regress/**'

jobs:
    centos:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["quay.io/centos/centos:centos7"]

        # CentOS images come from quay.io now
        container:
            image: ${{ matrix.container }}
            credentials:
                username: ${{ secrets.QUAY_IO_USERNAME }}
                password: ${{ secrets.QUAY_IO_PASSWORD }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Requirements before the git clone can happen
            - name: git clone requirements
              run: |
                  yum upgrade -y
                  yum install -y epel-release git

            # This means clone the git repo
            - uses: actions/checkout@v2

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  # Install make(1) so we can use the instreqs target
                  yum install -y make

                  # Install build dependencies and set up the target
                  make instreqs

                  # Build and run the test suite
                  # Make sure /usr/local is in the PATH
                  export PATH=${PATH}:/usr/local/bin

                  # Make sure to use the specific newer Python
                  PYTHON_PROG="$(cd /usr/local/bin ; ls -1 python*.* | grep -v config)"

                  # Do a debug build and run the test suite
                  make debug PYTHON="${PYTHON_PROG}"
                  env LANG=en_US.UTF-8 make check PYTHON="${PYTHON_PROG}"

                  # Report coverage
                  ninja -C build coverage && ( curl -s https://codecov.io/bash | bash ) || :
