name: CentOS

on:
    push:
        branches: [ master ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'

jobs:
    centos:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        #
        # Once EPEL-9 is filled out more, add c9s to the mix:
        #     "quay.io/centos/centos:stream9"
        strategy:
            matrix:
                container: ["quay.io/centos/centos:stream8",
                            "quay.io/centos/centos:centos7"]

        # CentOS images come from quay.io now
        container:
            image: ${{ matrix.container }}
            credentials:
                username: ${{ secrets.QUAY_IO_USERNAME }}
                password: ${{ secrets.QUAY_IO_PASSWORD }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Requirements before the git clone can happen
            - name: git clone requirements
              run: |
                  case "${{ matrix.container }}" in
                      *stream9)
                          dnf install -y 'dnf-command(config-manager)'
                          dnf config-manager --set-enabled crb
                          dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
                                      https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
                          ;;
                      *)
                          yum install -y epel-release
                          ;;
                  esac

                  if [ -d /etc/pki/rpm-gpg ]; then
                      rpm --import /etc/pki/rpm-gpg/*
                  fi

                  yum install -y git

            # This means clone the git repo
            - uses: actions/checkout@v2.1.0

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  # Install make(1) so we can use the instreqs target
                  yum install -y make

                  # Install build dependencies and set up the target
                  make instreqs

                  # Build the software and run the test suite
                  case "${{ matrix.container }}" in
                      *centos7)
                          # Make sure /usr/local is in the PATH
                          export PATH=${PATH}:/usr/local/bin

                          # Make sure to use the specific newer Python
                          PYTHON_PROG="$(cd /usr/local/bin ; ls -1 python*.* | grep -v config)"

                          meson setup build --werror -D python_program="${PYTHON_PROG}" -D b_buildtype=debug -D b_coverage=true
                          ninja -C build -v
                          env LANG=en_US.UTF-8 meson test -C build -v
                          ninja -C build coverage
                          curl -s https://codecov.io/bash | bash
                          ;;
                      *)
                          meson setup build --werror -D b_buildtype=debug -D b_coverage=true
                          ninja -C build -v
                          env LANG=en_US.UTF-8 meson test -C build -v
                          ninja -C build coverage
                          curl -s https://codecov.io/bash | bash
                          ;;
                  esac
