name: CI

on:
    push:
        branches: [ master ]
        paths-ignore:
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

    pull_request:
        branches: [ master ]
        paths-ignore:
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

jobs:
    # Fedora on x86_64
    x86_64:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["fedora:rawhide", "fedora:latest"]

        container:
            image: ${{ matrix.container }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v2.1.0

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  case "${{ matrix.container }}" in
                      fedora*)
                          dnf install -y make
                          ;;
                  esac
                  make instreqs
                  meson setup build --werror -Db_buildtype=debug -Db_coverage=true
                  ninja -C build -v
                  meson test -C build -v
                  ninja -C build coverage
                  curl -s https://codecov.io/bash | bash
