name: CI

on:
    push:
        branches: [ master ]
        paths-ignore:
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

    pull_request:
        branches: [ master ]
        paths-ignore:
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

jobs:
    # Fedora on x86_64
    x86_64:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["fedora:rawhide", "fedora:latest"]

        container:
            image: ${{ matrix.container }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v2.1.0

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  case "${{ matrix.container }}" in
                      fedora*)
                          dnf install -y make
                          ;;
                  esac
                  make instreqs
                  meson setup build --werror -Db_buildtype=debug -Db_coverage=true
                  ninja -C build -v
                  meson test -C build -v
                  ninja -C build coverage
                  curl -s https://codecov.io/bash | bash

    # Non-x86_64 architectures for Fedora, Ubuntu, Debian, Arch, and Alpine
    other_arches:
        # GitHub Actions offers Ubuntu to run the job.
        runs-on: ubuntu-latest
        name: Build and test on ${{ matrix.distro }} ${{ matrix.arch }}

        # Run steps on a matrix of arch/distro combinations
        strategy:
            matrix:
                include:
                    - arch: aarch64
                      distro: fedora_latest

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v2.1.0
            - uses: uraimo/run-on-arch-action@v2.0.5
              name: buildtest
              id: buildtest
              timeout-minutes: 500
              with:
                  arch: ${{ matrix.arch }}
                  distro: ${{ matrix.distro }}
                  githubToken: ${{ github.token }}

                  # The shell to run commands with in the container
                  shell: /bin/sh

                  # Within the container, install the dependencies
                  # required to use our Makefile
                  install: |
                      case "${{ matrix.distro }}" in
                          fedora*)
                              dnf install -y make
                              ;;
                          debian*|buster|stretch|jessie)
                              apt-get update
                              apt-get -y install make
                              ;;
                      esac

                  # Build the software and run the test suite
                  run: |
                      make instreqs
                      meson setup build --werror -Db_buildtype=debug -Db_coverage=true
                      ninja -C build -v
                      meson test -C build -v
                      curl -s https://codecov.io/bash | bash
