name: FreeBSD

on:
    push:
        branches: [ main ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

jobs:
    freebsd:
        # Use containers on this specific macos image
        # https://github.com/marketplace/actions/freebsd-vm
        runs-on: macos-12

        # Environment variables for the job
        env:
            PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v3

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              uses: vmactions/freebsd-vm@v0

              with:
                  envs: 'PATH'
                  usesh: true

                  # Requirements before the git clone can happen
                  prepare: |
                      pkg update
                      pkg install -y git
                      git config --global --add safe.directory /__w/rpminspect/rpminspect

                  # Run the build and test
                  run: |
                      # Install GNU make(1) so we can use the instreqs target
                      pkg install -y gmake

                      # Store exit codes for each step here for use in the next step
                      mkdir -p exitcodes

                      # Install build dependencies and set up the target
                      gmake instreqs
                      echo $? > exitcodes/instreqs

                      # Build the software and run the test suite
                      env CC=gcc CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib gmake debug
                      echo $? > exitcodes/build
                      gmake check
                      echo $? > exitcodes/test
                      ninja -C build coverage && ( curl -s https://codecov.io/bash | bash ) || :
                      mv exitcodes build

            # Process the exit codes outside the VM
            - name: Check exit codes
              run: |
                  for ec in exitcodes/* ; do
                      code="$(cat ${ec} 2>/dev/null)"
                      [ -z "${code}" ] && code=0
                      [ ${code} -eq 0 ] || exit ${code}
                  done
