name: FreeBSD

on:
    push:
        branches: [ main ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

    pull_request:
        branches: [ main ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'
        - 'utils/**'

jobs:
    freebsd:
        # Use containers on this specific macos image
        # https://github.com/marketplace/actions/freebsd-vm
        runs-on: macos-12

        # Environment variables for the job
        env:
            PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/sbin

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # This means clone the git repo
            - uses: actions/checkout@v3

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              uses: vmactions/freebsd-vm@v0

              with:
                  envs: 'PATH'
                  usesh: true

                  # Requirements before the git clone can happen
                  prepare: |
                      pkg install -y git
                      git config --global --add safe.directory /__w/rpminspect/rpminspect
                  # Run the build and test
                  run: |
                      # Install GNU make(1) so we can use the instreqs target
                      pkg install -y gmake

                      # Install build dependencies and set up the target
                      gmake instreqs

                      # Build the software and run the test suite
                      env CFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib meson setup build --werror -D b_buildtype=debug -D b_coverage=true -D with_libkmod=false -D with_libcap=false -D with_annocheck=false
                      ninja -C build -v
                      env LANG=en_US.UTF-8 meson test -C build -v
                      ninja -C build coverage
                      curl -s https://codecov.io/bash | bash
