name: Oracle Linux

on:
    push:
        branches: [ main ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'

jobs:
    linux:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["oraclelinux:8"]

        container:
            image: ${{ matrix.container }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Requirements before the git clone can happen
            - name: git clone requirements
              run: |
                  # Oracle's EPEL copy
                  mkdir -p /etc/yum.repos.d
                  echo '[ol8_developer_EPEL]' > /etc/yum.repos.d/ol8-epel.repo
                  echo 'name=Oracle Linux $releasever EPEL ($basearch)' >> /etc/yum.repos.d/ol8-epel.repo
                  echo 'baseurl=https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/$basearch/' >> /etc/yum.repos.d/ol8-epel.repo
                  echo 'gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle' >> /etc/yum.repos.d/ol8-epel.repo
                  echo 'gpgcheck=1' >> /etc/yum.repos.d/ol8-epel.repo
                  echo 'enabled=1' >> /etc/yum.repos.d/ol8-epel.repo

                  # Turn on all the other repos
                  sed -i -e 's|enabled=0|enabled=1|g' /etc/yum.repos.d/oracle-linux-ol8.repo

                  dnf install -y git
                  git config --global --add safe.directory /__w/rpminspect/rpminspect

            # This means clone the git repo
            - uses: actions/checkout@v3

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  # Install make(1) so we can use the instreqs target
                  dnf install -y make

                  # Install build dependencies and set up the target
                  make instreqs

                  # Build the software and run the test suite
                  meson setup build --werror -D b_buildtype=debug -D b_coverage=true
                  ninja -C build -v
                  env LANG=en_US.UTF-8 meson test -C build -v
                  ninja -C build coverage && ( curl -s https://codecov.io/bash | bash ) || :
