name: Slackware Linux

on:
    push:
        branches: [ master ]
        paths-ignore:
        - AUTHORS.md
        - CC-BY-4.0.txt
        - CODE_OF_CONDUCT.md
        - COPYING
        - COPYING.LIB
        - HISTORY
        - LICENSE-2.0.txt
        - MISSING
        - README.md
        - TODO
        - 'contrib/**'
        - 'data/**'
        - 'doc/**'
        - 'po/**'
        - 'regress/**'

jobs:
    linux:
        # Use containers on their ubuntu latest image
        runs-on: ubuntu-latest

        # Set up the matrix of distributions to test
        strategy:
            matrix:
                container: ["vbatts/slackware:current"]

        container:
            image: ${{ matrix.container }}

        # All of these steps run from within the main source
        # directory, so think of that as your $PWD
        steps:
            # Make sure slackpkg works
            - name: Configure slackpkg
              run: |
                  # Use the versioned release available
                  . /etc/os-release
                  sed -i '$d' /etc/slackpkg/mirrors
                  echo "http://slackware.osuosl.org/slackware64-${VERSION_ID}/" >> /etc/slackpkg/mirrors

                  # Enable batch mode
                  sed -i -e 's/^BATCH=.*$/BATCH=on/g' /etc/slackpkg/slackpkg.conf
                  sed -i -e 's/^DEFAULT_ANSWER=.*$/DEFAULT_ANSWER=y/g' /etc/slackpkg/slackpkg.conf

                  # slackpkg needs knowledge
                  slackpkg update

            # Requirements before the git clone can happen
            - name: git clone requirements
              run: |
                  slackpkg install git nghttp2 brotli cyrus-sasl dcron perl ca-certificates
                  update-ca-certificates --fresh

            # This means clone the git repo
            - uses: actions/checkout@v2.1.0

            # Within the container, install the dependencies, build,
            # and run the test suite
            - name: Build and run the test suite
              run: |
                  # Install make(1) so we can use the instreqs target
                  slackpkg install guile gc make

                  # Install build dependencies and set up the target
                  make instreqs

                  # Build the software and run the test suite
                  meson setup build --werror -D b_buildtype=debug -D b_coverage=true
                  ninja -C build -v
                  env LANG=en_US.UTF-8 meson test -C build -v
                  ninja -C build coverage
                  curl -s https://codecov.io/bash | bash
