name: Style Checks

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    shellcheck:
        runs-on: ubuntu-latest
        # Ubuntu's ShellCheck is old enough to not have --severity
        container: fedora:latest
        steps:
            - uses: actions/checkout@v2
            - run: dnf install -y ShellCheck xz
            - run: shellcheck --severity=warning **/*.sh
    python:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                tox_job: ["flake8", "format"]
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install tox
            - name: Checking Python code with ${{ matrix.tox_job }}
              run: tox -e ${{ matrix.tox_job }}
